### ISSUE TITLE
Error with load_solution "failed to read inputs of provider operator"

### ISSUE THREAD

**Issue by maxotar** [pyansys/pydpf-post#29] opened 2021-09-10 19:24 UTC
```
from ansys.dpf import post
solution = post.load_solution("file.rst")
```

```
Traceback (most recent call last):
  File "c:/Users/d57151/Repos/Test/test_dpf_post.py", line 3, in <module>
    solution = post.load_solution("Blisk.rst")
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\post\post_utility.py", line 29, in load_solution
    _model = Model(data_sources)
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\core\model.py", line 52, in __init__
    self._metadata = Metadata(data_sources, self._server)
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\core\model.py", line 229, in __init__
    self._cache_result_info()
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\core\model.py", line 233, in _cache_result_info
    self.result_info = self._load_result_info()
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\core\model.py", line 351, in _load_result_info
    result_info = op.get_output(0, types.result_info)
  File "C:\Users\d57151\Miniconda3\envs\pyansys\lib\site-packages\ansys\dpf\core\errors.py", line 103, in wrapper
    raise DPFServerException(details) from None
ansys.dpf.core.errors.DPFServerException: ResultInfoProvider<-mapdl::rst::ResultInfoProvider<-mapdl::rst::ResultInfoProvider<-TimeFreqSupportProvider<-mapdl::rst::TimeFreqSupportProvider<-mapdl::rst::TimeFreqSupportProvider<-Unable to open the following file: file.rst, failed to read inputs of provider operator
```

The file is readable with this
```
from ansys.mapdl import reader as pymapdl_reader
rst = pymapdl_reader.read_binary("file.rst")
rst.plot_principal_nodal_stress(rnum=0, comp="SEQV")
```

[file.zip](https://github.com/pyansys/DPF-Post/files/7145887/file.zip)

**Comment by akaszynski** [comment] 2021-09-10 19:38
Try using an absolute file path when loading the file since the server doesn't know of the relative file location from python.

This is a feature we should add.

**Comment by maxotar** [comment] 2021-09-10 19:46
Absolute path seems to have fixed that issue because I am able to load "ASimpleBar.rst" from the example files.

But now I get this error (with my file.rst):
`ansys.dpf.core.errors.DPFServerException: ResultInfo_GetUnitSystemName error : -Unknown exception occured-`

**Comment by rlagha** [comment] 2021-09-10 20:04
@maxotar  please could you tell us what is the version of ansys.dpf.post that you are using?

**Comment by maxotar** [comment] 2021-09-10 20:20
@rlagha 
ansys-dpf-core            0.3.0
ansys-dpf-post            0.2.0

**Comment by rlagha** [comment] 2021-09-10 20:41
@maxotar may I ask you to share your rst file if this is possible? I created a rst file without units but this worked on my side.

**Comment by maxotar** [comment] 2021-09-10 20:56
@rlagha The rst is zipped and in my first post. The rst is from a solved Workbench model.

**Comment by rlagha** [comment] 2021-09-10 21:29
thanks @maxotar for finding this, there is an issue in the server side, we will fix it and keep you updated. 
As a workaround you can do it this way:

**import ansys.dpf.core as dpf

ds = dpf.DataSources(r"C:\temp\file.rst")
streamP = dpf.operators.metadata.streams_provider(ds)

s = dpf.operators.result.stress_von_mises()
s.inputs.streams_container.connect(streamP.outputs)
field = s.outputs.fields_container()[0]
field.data**

if you want to plot the countour: 
**meshP = dpf.operators.mesh.mesh_provider()
meshP.inputs.streams_container.connect(streamP.outputs)
mesh = meshP.outputs.mesh()
mesh.plot(field)**

please do not hesitate if you have any question.

**Comment by PProfizi** [comment] 2022-03-11 10:42
Hi @maxotar @rlagha . I could not reproduce the error with the latest versions of PyDPF-Core and PyDPF-Post so considering the date I assume this has been solved. 
If OK with all I will be closing this issue.

**Closed** 2022-03-18 12:48 UTC
