### ISSUE TITLE
ansys.dpf.core.errors.DPFServerException: failed to connect to all addresses

### ISSUE THREAD

**Issue by Roehrich** [pyansys/pydpf-post#19] opened 2021-02-08 11:34 UTC
Hi,
I'm experiencing problems while accessing the solution for shell 281.
everything seems to work fine until I dive into the strainresults e.g. with:
solution = post.load_solution(r'......files\dp0\SYS-3\MECH\file.rst')
strain = solution.elastic_strain()
ex = strain.xx
As soon as I reach the last line I get the above error. I could not figure out what it meands. I tried a lot of differnt approaches, nothing works. Sometimes I get a different error "stream removed".
Any help would be apprechiated,
Best Regards

**Comment by akaszynski** [comment] 2021-02-08 13:35
I'll agree that the error is a bit obscure.  It's possible that either there's a bug with DPF service and how it's calculating the results or the way we're talking with the service.  Would it be possible for you to upload the result file here to determine the root cause?

**Comment by Roehrich** [comment] 2021-02-08 15:02
Sure, please find attached the rst file.

[file.zip](https://github.com/pyansys/DPF-Post/files/5944461/file.zip)

**Comment by rlagha** [comment] 2021-02-16 08:10
Hi @Roehrich ,
In fact this is an issue in the server side, sorry for that, I'll investigate and get back to you.
Best Regards
Ramdane

**Comment by Roehrich** [comment] 2021-02-16 19:10
Thanks a lot for the update.
I‘m looking forward to hear of any solution.

**Comment by PProfizi** [comment] 2022-03-11 10:37
Hi @rlagha @akaszynski @Roehrich . I could not reproduce the error using the up-to-date version of PyDPF-Post and PyDPF-Core, so considering the date I assume it has been corrected since.
If OK with everyone I will be closing this issue.

**Closed** 2022-03-18 12:48 UTC
