### ISSUE TITLE
OpenGL error

### ISSUE THREAD

**Issue by lionel-wilhelm** [pyansys/pydpf-post#44] opened 2021-11-02 15:47 UTC
Dear Dev team,
I tried to install dpf-post on my Windows machine in a conda environment which actually worked. The machine has Ansys 2021R2 installed.
When I run the following lines everything goes well : 
```
>>> from ansys.dpf import post
>>> from ansys.dpf.post import examples
>>> solution = post.load_solution(examples.multishells_rst)
>>> stress = solution.stress()
```
But when I try to plot something (with `stress.xx.plot_contour(show_edges=False)`) I get the following errors :
```
2021-11-02 15:33:06.742 (  71.091s) [                ]vtkWin32OpenGLRenderWin:635    ERR| vtkWin32OpenGLRenderWindow (0000028F1855D980): failed to get wglChoosePixelFormatARB
ERROR:root:failed to get wglChoosePixelFormatARB
2021-11-02 15:33:06.745 (  71.093s) [                ]vtkWin32OpenGLRenderWin:713    ERR| vtkWin32OpenGLRenderWindow (0000028F1855D980): failed to get valid pixel format.
ERROR:root:failed to get valid pixel format.
2021-11-02 15:33:06.745 (  71.094s) [                ]vtkOpenGLRenderWindow.c:569    ERR| vtkWin32OpenGLRenderWindow (0000028F1855D980): GLEW could not be initialized: Missing GL version
ERROR:root:GLEW could not be initialized: Missing GL version
```
and the kernel crashes.

If you don't have a way of solving this, what is the preferred environment to use the ansys.dpf.post package especially for plotting ?It seems to me that you use pyvista objects. Could you tell me if the plots could be interactive with the appropriate JupyterLab backend (https://docs.pyvista.org/user-guide/jupyter/index.html) ? 
Thanks in advance, best regards,
Lionel Wilhelm

**Comment by rlagha** [comment] 2021-11-03 08:03
Hi @lionel-wilhelm , 
We are using pyVista as a default viewer in dpf modules. The issue you are seeing looks like an Open GL issue. Please could you give us more details on your system configuration? This will help us to try reproducing this issue.
@akaszynski

**Comment by lionel-wilhelm** [comment] 2021-11-03 09:05
Dear @rlagha,
thanks for your answer. I'm working on an Azure machine (Standard D4s v3 on Windows 10). Regarding my python environment, please find attached the `environment.log` (YAML file) file resulting from `conda export > environment.log`
[environment.log](https://github.com/pyansys/pydpf-post/files/7466242/environment.log)

I had similar problems on the this azure machine while working with Paraview. I solved this following by using Mesa (see here [https://discourse.paraview.org/t/how-to-run-paraview-including-the-binary-release-using-mesa-on-windows/4321](https://discourse.paraview.org/t/how-to-run-paraview-including-the-binary-release-using-mesa-on-windows/4321))

I also found that Azure machines do not natively support OpenGL (https://stackoverflow.com/questions/48433641/does-azure-allow-app-need-opengl-any-way-to-go-around).

I also get the same error when running some examples of the Pyvista documentation. I guess it's only OpenGL related. I will dig into this problem and share a solution if I find one. 

If you don't have time to look into this issue, you can close it. 

Thanks,
Lionel

**Comment by akaszynski** [comment] 2021-11-05 16:26
Hello,

Sorry about the late reply.  The trick with OpenGL on Azure VMs is to use:

https://github.com/pyvista/gl-ci-helpers/blob/master/appveyor/install_opengl.ps1

This installs the OSMesa OpenGL that uses software rendering.

**Comment by PProfizi** [comment] 2022-03-11 17:06
Hi @lionel-wilhelm , I am reviewing the Issues and this one seems to have answered the question, can you confirm?
If OK with everyone I'll close this Issue in a few days.

**Closed** 2022-03-23 08:44 UTC
